In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("01-Ad.csv")

In [3]:
df.shape

(400, 6)

In [4]:
df.head()

   UserID  Gender Type  Age  EstimatedSalary  Purchased
0       1    Male    B   24          2800000          0
1       2    Male    A   48          3000000          0
2       3  Female    B   34          7800000          0
3       4  Female    B   36         10700000          0
4       5    Male    D   24         14700000          0

# nokte
Model miad inja az UserID och Purchased(target) ke estefade nemikone pas miaim ina ro drop mikonim

In [15]:
#miam az Age och EstimatedSalary estefade mikonim bara sadegi kar chon adad hast asoon tare
#mamoolan chizayi ke mikham bedim be model ro ba x va chizayi ke mikhaim pishini konim mishe y
#in yaeni kole satrha ama sotun 3 ta 4(khode 5 hesab nemishe)
x = df.iloc[:,3:5].values
#yaeni az in df ke dorost kardi man maghadiresho mikham be esme sotun o in dastana kar nadaram
print(x)

[[      24  2800000]
 [      48  3000000]
 [      34  7800000]
 [      36 10700000]
 [      24 14700000]
 [      36 10900000]
 [      36 16300000]
 [      44 30000000]
 [      33  5700000]
 [      48 12400000]
 [      34 15500000]
 [      34  9700000]
 [      25 16700000]
 [      44  2600000]
 [      22 15900000]
 [      39 15500000]
 [      67  4100000]
 [      64  4300000]
 [      65  4700000]
 [      68  4900000]
 [      64  3500000]
 [      67  9100000]
 [      68  7400000]
 [      64  3500000]
 [      65  3700000]
 [      67  3000000]
 [      70  4700000]
 [      67  5100000]
 [      39  7800000]
 [      42  2600000]
 [      42 14200000]
 [      36 27300000]
 [      27  2200000]
 [      37  8000000]
 [      36 17600000]
 [      48  4500000]
 [      45  4700000]
 [      41  9100000]
 [      34 13800000]
 [      36  5300000]
 [      36  2400000]
 [      45  9500000]
 [      48 21300000]
 [      41  2000000]
 [      37 16300000]
 [      30  3000000]
 [      33 15300000]
 [      36 10100000]
 [      41 26900000]
 [      42 17300000]
 [      31  5500000]
 [      22  8000000]
 [      39 16100000]
 [      48  3700000]
 [      36 10900000]
 [      31 10300000]
 [      30  8800000]
 [      37 15300000]
 [      28  2600000]
 [      44 23200000]
 [      36  3000000]
 [      33 16900000]
 [      30 12600000]
 [      44 23800000]
 [      85 16100000]
 [      31 10900000]
 [      31  2800000]
 [      30 15900000]
 [      28 12000000]
 [      42 13000000]
 [      33 15500000]
 [      31  4500000]
 [      25  3700000]
 [      45 22300000]
 [      44  2600000]
 [      47 22100000]
 [      22  9700000]
 [      28  4500000]
 [      37 16900000]
 [      34  2400000]
 [      41 15500000]
 [      54  7600000]
 [      25  9100000]
 [      48 17100000]
 [      41 11700000]
 [      42 23400000]
 [      31 10300000]
 [      37 16500000]
 [      34 15700000]
 [      48  9300000]
 [      28 15700000]
 [      41 22900000]
 [      34  2000000]
 [      39  4700000]
 [      39 16100000]
 [      48  8000000]
 [      48  4100000]
 [      37 24400000]
 [      48 14000000]
 [      37  6600000]
 [      36 17100000]
 [      37 11100000]
 [      44 16700000]
 [      45 29800000]
 [      24  3200000]
 [      27 13800000]
 [      34  6100000]
 [      36 17300000]
 [      34 16700000]
 [      53 15500000]
 [      54 13600000]
 [      51 13600000]
 [      53 11500000]
 [      51 10300000]
 [      59 15500000]
 [      56 10700000]
 [      48 14400000]
 [      50  9700000]
 [      56 11100000]
 [      58 11100000]
 [      50 14400000]
 [      51 13800000]
 [      56 14400000]
 [      48  9900000]
 [      58  9500000]
 [      54 11500000]
 [      59 12400000]
 [      34  5500000]
 [      41  2400000]
 [      34 16300000]
 [      42 10900000]
 [      45  5300000]
 [      41 16900000]
 [      27 13000000]
 [      37 10300000]
 [      30 12000000]
 [      25 15900000]
 [      41 21100000]
 [      37 11100000]
 [      24  4100000]
 [      24 16500000]
 [      22 13000000]
 [      48 11100000]
 [      41 17300000]
 [      47  4100000]
 [      31 17300000]
 [      36 18800000]
 [      58  5100000]
 [      39 11500000]
 [      25 14200000]
 [      34  2000000]
 [      58  8200000]
 [      42 14700000]
 [      50  9300000]
 [      56  8600000]
 [      42  2000000]
 [      65 11100000]
 [      39 14400000]
 [      34  5100000]
 [      44 26900000]
 [      44 19600000]
 [      33 17600000]
 [      51  5700000]
 [      48  6800000]
 [      45 13200000]
 [      22 16700000]
 [      28 10300000]
 [      48 13600000]
 [      39 29600000]
 [      39  8600000]
 [      27 17100000]
 [      47 22700000]
 [      34 23400000]
 [      47  7800000]
 [      47 13800000]
 [      30  4700000]
 [      48  8600000]
 [      33  3500000]
 [      31  3700000]
 [      42  5900000]
 [      34  2200000]
 [      42 13600000]
 [      44 23200000]
 [      45  7800000]
 [      45 11300000]
 [      42 12600000]
 [      25 15900000]
 [      45  7400000]
 [      48 13800000]
 [      37  5500000]
 [      31 16300000]
 [      24  4300000]
 [      39  7800000]
 [      24 13400000]
 [      37 17300000]
 [      47  7800000]
 [      41 15300000]
 [      25  6400000]
 [      34 15500000]
 [      48  3500000]
 [      48  7000000]
 [      70 14200000]
 [      54 26700000]
 [      58 13600000]
 [      84 19800000]
 [      67  8600000]
 [      79 25900000]
 [      75 22500000]
 [      56 28300000]
 [      65  3500000]
 [      68 18800000]
 [      75 30000000]
 [      85  7600000]
 [      48 10900000]
 [      67  7800000]
 [      87 21300000]
 [      70 12400000]
 [      56 15100000]
 [      65 18800000]
 [      85 28500000]
 [      58 15500000]
 [      48 17800000]
 [      51 28800000]
 [      87 20000000]
 [      48 11300000]
 [      51  9900000]
 [      50 25000000]
 [      81 26500000]
 [      56 13800000]
 [      59 15500000]
 [      48 29400000]
 [      54  7600000]
 [      56 21100000]
 [      70 16700000]
 [      53 22100000]
 [      65 15300000]
 [      56 10700000]
 [      51 15500000]
 [      65 15900000]
 [      76 28500000]
 [      59 29800000]
 [      53 11100000]
 [      72 17100000]
 [      81 20500000]
 [      58 13800000]
 [      73 29200000]
 [      48  9300000]
 [      82 24200000]
 [      58  9700000]
 [      48 19000000]
 [      62  7000000]
 [      51  9700000]
 [      68 26700000]
 [      51 29200000]
 [      72  8000000]
 [      75 17600000]
 [      58 13800000]
 [      56 10700000]
 [      84 18600000]
 [      64 26100000]
 [      48 14900000]
 [      50 28800000]
 [      79 24800000]
 [      48 13800000]
 [      68 17600000]
 [      59 21300000]
 [      56 14400000]
 [      51 14200000]
 [      67 28800000]
 [      56 11500000]
 [      61 26500000]
 [      85 14700000]
 [      87  7600000]
 [      54 20900000]
 [      82  4300000]
 [      82 14200000]
 [      53 13600000]
 [      70 17100000]
 [      75  6800000]
 [      72  6400000]
 [      85 17100000]
 [      48 11500000]
 [      51 13400000]
 [      75  3200000]
 [      68 28100000]
 [      51 18200000]
 [      51 11700000]
 [      68 27500000]
 [      58 15300000]
 [      51 15100000]
 [      54 26700000]
 [      70 17300000]
 [      79  7000000]
 [      51 14900000]
 [      48 10700000]
 [      50 12000000]
 [      59 14000000]
 [      61 22100000]
 [      64 15300000]
 [      65 23200000]
 [      84  6800000]
 [      68 14200000]
 [      51 27300000]
 [      51 15300000]
 [      56 11300000]
 [      59 10100000]
 [      73 26700000]
 [      67 22300000]
 [      50 24800000]
 [      53  9300000]
 [      59 13400000]
 [      54 18800000]
 [      53  9300000]
 [      70 28100000]
 [      54 15300000]
 [      54 14400000]
 [      78 20500000]
 [      48 10300000]
 [      64  5500000]
 [      50 11300000]
 [      75 27500000]
 [      76 15900000]
 [      58  9700000]
 [      68  5100000]
 [      68 26100000]
 [      58 11300000]
 [      58 13800000]
 [      59 14400000]
 [      50 23400000]
 [      67 21100000]
 [      53  9500000]
 [      68 23600000]
 [      59 12400000]
 [      56 12400000]
 [      82 11300000]
 [      50 10100000]
 [      84 28800000]
 [      48 15300000]
 [      53 10300000]
 [      54 24200000]
 [      76 20500000]
 [      48 14400000]
 [      53 12400000]
 [      67  9500000]
 [      67 20700000]
 [      58 12000000]
 [      76 13800000]
 [      78 21300000]
 [      54 14900000]
 [      53 11500000]
 [      53 22300000]
 [      51 14400000]
 [      59 17600000]
 [      51 10700000]
 [      50 19400000]
 [      87  5900000]
 [      78 13400000]
 [      58 13800000]
 [      56 13600000]
 [      59 10100000]
 [      61 25600000]
 [      76  5900000]
 [      67  9300000]
 [      59 15300000]
 [      59 20500000]
 [      85  4900000]
 [      84  8600000]
 [      65 17100000]
 [      53 13600000]
 [      78  4300000]
 [      87  8400000]
 [      87 16100000]
 [      54 14000000]
 [      85 25900000]
 [      51 15500000]
 [      65  5500000]
 [      65 14200000]
 [      59  9900000]
 [      58 16900000]
 [      84  3700000]
 [      59 12200000]
 [      68  5700000]
 [      62 27700000]
 [      70  4700000]
 [      82  5700000]
 [      81 11300000]
 [      70  7000000]
 [      54 13600000]
 [      67  5900000]
 [      68  6100000]
 [      68  5700000]
 [      67  3700000]
 [      64  8200000]
 [      87  7600000]
 [      54 11100000]
 [      65  7400000]
 [      73  3700000]
 [      72  3000000]
 [      50  5700000]
 [      70  6400000]]

In [14]:
# .values nazari dataframe mishe ke header inash miad ama ba .values mishe ye matrix ba in maghadir
#y = df.iloc[:,5].values
y = df.iloc[:,-1].values
#in rahat tare nemikhad do saat berim beshmorim

In [ ]:
#mamaad